In [4]:
import pandas as pd

df = pd.read_csv("cardio_train.csv", sep=';')
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [5]:
df.shape

(70000, 13)

In [6]:
df.columns

Index(['id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo',
       'cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [8]:
df.describe()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,49972.419900,19468.865814,1.349571,164.359229,74.205690,128.817286,96.630414,1.366871,1.226457,0.088129,0.053771,0.803729,0.499700
std,28851.302323,2467.251667,0.476838,8.210126,14.395757,154.011419,188.472530,0.680250,0.572270,0.283484,0.225568,0.397179,0.500003
min,0.000000,10798.000000,1.000000,55.000000,10.000000,-150.000000,-70.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,25006.750000,17664.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,50001.500000,19703.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,74889.250000,21327.000000,2.000000,170.000000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,99999.000000,23713.000000,2.000000,250.000000,200.000000,16020.000000,11000.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
df['age_years'] = (df['age'] / 365).astype(int)
df.drop(columns=['age'], inplace=True)

In [10]:
df.isnull().sum()

id             0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
age_years      0
dtype: int64

In [11]:
df[['height','weight','ap_hi','ap_lo']].describe()

             height        weight         ap_hi         ap_lo
count  70000.000000  70000.000000  70000.000000  70000.000000
mean     164.359229     74.205690    128.817286     96.630414
std        8.210126     14.395757    154.011419    188.472530
min       55.000000     10.000000   -150.000000    -70.000000
25%      159.000000     65.000000    120.000000     80.000000
50%      165.000000     72.000000    120.000000     80.000000
75%      170.000000     82.000000    140.000000     90.000000
max      250.000000    200.000000  16020.000000  11000.000000

In [13]:
df = df[(df['height'] >= 120) & (df['height'] <= 220)]
df = df[(df['weight'] >= 30) & (df['weight'] <= 200)] 

# Removing unrealistic height values
# Removing unrealistic weight values

In [14]:
df = df[(df['ap_hi'] >= 90) & (df['ap_hi'] <= 250)]
df = df[(df['ap_lo'] >= 60) & (df['ap_lo'] <= 150)]      # Removing invalid blood pressure readings

In [ ]:
df = df[df['ap_hi'] > df['ap_lo']]
# Ensuring systolic BP is greater than diastolic BP

In [ ]:
df.shape

In [19]:
df.isnull().sum()

id             0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
age_years      0
dtype: int64

In [21]:
df['cardio'].value_counts()

cardio
0    34548
1    33888
Name: count, dtype: int64

In [22]:
pd.crosstab(df['gender'], df['cardio'], normalize='index')

cardio         0         1
gender
1       0.507362  0.492638
2       0.500084  0.499916

In [23]:
df[['cholesterol', 'gluc']].value_counts()

cholesterol  gluc
1            1       47671
2            1        6538
3            1        3972
             3        3381
2            2        2354
1            2        2193
             3        1457
3            2         500
2            3         370
Name: count, dtype: int64

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 68436 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           68436 non-null  int64
 1   gender       68436 non-null  int64
 2   height       68436 non-null  int64
 3   weight       68436 non-null  float64
 4   ap_hi        68436 non-null  int64
 5   ap_lo        68436 non-null  int64
 6   cholesterol  68436 non-null  int64
 7   gluc         68436 non-null  int64
 8   smoke        68436 non-null  int64
 9   alco         68436 non-null  int64
 10  active       68436 non-null  int64
 11  cardio       68436 non-null  int64
 12  age_years    68436 non-null  int32
dtypes: float64(1), int32(1), int64(11)
memory usage: 7.0 MB

In [25]:
df = df.drop(columns=['id'])

In [26]:
df.shape

(68436, 12)

In [27]:
X = df.drop(columns=['cardio'])
y = df['cardio']

X.shape, y.shape 

#separate independent variables (X) and dependent variable (y) before training ML models

((68436, 11), (68436,))

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_train.shape, X_test.shape          #stratify=y

 #it keeps heart disease ratio same in train & test.
#Stratification prevents class imbalance during splitting.

((54748, 11), (13688, 11))

In [29]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
#FOR LOGISTIC REGRESSION

In [30]:
#Logistic Regression (Baseline Model)
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [31]:
#Model Evaluation
from sklearn.metrics import accuracy_score, classification_report

y_pred = lr.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7290327293980129
              precision    recall  f1-score   support

           0       0.71      0.79      0.75      6910
           1       0.76      0.67      0.71      6778

    accuracy                           0.73     13688
   macro avg       0.73      0.73      0.73     13688
weighted avg       0.73      0.73      0.73     13688

In [32]:
pip install interpret

Requirement already satisfied: interpret in c:\users\asus\anaconda3\lib\site-packages (0.7.3)
Requirement already satisfied: interpret-core==0.7.3 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.7.3)
Requirement already satisfied: numpy>=1.25 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core==0.7.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (1.26.4)
Requirement already satisfied: pandas>=0.19.2 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core==0.7.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.2.2)
Requirement already satisfied: scikit-learn>=0.18.1 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core==0.7.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (1.4.2)
Requirement already satisfied: joblib>=0.11 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core==0.7.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (1.4.2)
Requirement already satisfied: psutil>=5.6.2 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (5.9.0)
Requirement already satisfied: ipykernel>=4.10.0 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (6.28.0)
Requirement already satisfied: ipython>=5.5.0 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (8.25.0)
Requirement already satisfied: plotly>=3.8.1 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (5.22.0)
Requirement already satisfied: SALib>=1.3.3 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (1.5.1)
Requirement already satisfied: shap>=0.28.5 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.49.1)
Requirement already satisfied: dill>=0.2.5 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.4.0)
Requirement already satisfied: aplr>=10.6.1 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (10.17.1)
Requirement already satisfied: dash<3.0.0,>=2.0.0 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.18.2)
Requirement already satisfied: dash-cytoscape>=0.1.1 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (1.0.2)
Requirement already satisfied: gevent>=1.3.6 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (25.9.1)
Requirement already satisfied: requests>=2.19.0 in c:\users\asus\anaconda3\lib\site-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.32.2)
Requirement already satisfied: Flask<3.1,>=1.0.4 in c:\users\asus\anaconda3\lib\site-packages (from dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (3.0.3)
Requirement already satisfied: Werkzeug<3.1 in c:\users\asus\anaconda3\lib\site-packages (from dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (3.0.3)
Requirement already satisfied: dash-html-components==2.0.0 in c:\users\asus\anaconda3\lib\site-packages (from dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in c:\users\asus\anaconda3\lib\site-packages (from dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.0.0)
Requirement already satisfied: dash-table==5.0.0 in c:\users\asus\anaconda3\lib\site-packages (from dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (5.0.0)
Requirement already satisfied: importlib-metadata in c:\users\asus\anaconda3\lib\site-packages (from dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (7.0.1)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\asus\anaconda3\lib\site-packages (from dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (4.11.0)
Requirement already satisfied: retrying in c:\users\asus\anaconda3\lib\site-packages (from dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (1.4.2)
Requirement already satisfied: nest-asyncio in c:\users\asus\anaconda3\lib\site-packages (from dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (1.6.0)
Requirement already satisfied: setuptools in c:\users\asus\anaconda3\lib\site-packages (from dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (80.9.0)
Requirement already satisfied: greenlet>=3.2.2 in c:\users\asus\anaconda3\lib\site-packages (from gevent>=1.3.6->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (3.2.4)
Requirement already satisfied: cffi>=1.17.1 in c:\users\asus\anaconda3\lib\site-packages (from gevent>=1.3.6->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.0.0)
Requirement already satisfied: zope.event in c:\users\asus\anaconda3\lib\site-packages (from gevent>=1.3.6->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (6.0)
Requirement already satisfied: zope.interface in c:\users\asus\anaconda3\lib\site-packages (from gevent>=1.3.6->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (5.4.0)
Requirement already satisfied: comm>=0.1.1 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel>=4.10.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.2.1)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel>=4.10.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (1.6.7)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel>=4.10.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (8.6.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel>=4.10.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel>=4.10.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.1.6)
Requirement already satisfied: packaging in c:\users\asus\anaconda3\lib\site-packages (from ipykernel>=4.10.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (23.2)
Requirement already satisfied: pyzmq>=24 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel>=4.10.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (25.1.2)
Requirement already satisfied: tornado>=6.1 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel>=4.10.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (6.4.1)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\asus\anaconda3\lib\site-packages (from ipykernel>=4.10.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (5.14.3)
Requirement already satisfied: decorator in c:\users\asus\anaconda3\lib\site-packages (from ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\asus\anaconda3\lib\site-packages (from ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.18.1)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\asus\anaconda3\lib\site-packages (from ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\asus\anaconda3\lib\site-packages (from ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.15.1)
Requirement already satisfied: stack-data in c:\users\asus\anaconda3\lib\site-packages (from ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.2.0)
Requirement already satisfied: colorama in c:\users\asus\anaconda3\lib\site-packages (from ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\anaconda3\lib\site-packages (from pandas>=0.19.2->interpret-core==0.7.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\anaconda3\lib\site-packages (from pandas>=0.19.2->interpret-core==0.7.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\anaconda3\lib\site-packages (from pandas>=0.19.2->interpret-core==0.7.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2023.3)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\asus\anaconda3\lib\site-packages (from plotly>=3.8.1->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (8.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\asus\anaconda3\lib\site-packages (from requests>=2.19.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\asus\anaconda3\lib\site-packages (from requests>=2.19.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\asus\anaconda3\lib\site-packages (from requests>=2.19.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\asus\anaconda3\lib\site-packages (from requests>=2.19.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2024.7.4)
Requirement already satisfied: matplotlib>=3.5 in c:\users\asus\anaconda3\lib\site-packages (from SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (3.8.4)
Requirement already satisfied: multiprocess in c:\users\asus\anaconda3\lib\site-packages (from SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.70.18)
Requirement already satisfied: scipy>=1.9.3 in c:\users\asus\anaconda3\lib\site-packages (from SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (1.13.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\asus\anaconda3\lib\site-packages (from scikit-learn>=0.18.1->interpret-core==0.7.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.2.0)
Requirement already satisfied: tqdm>=4.27.0 in c:\users\asus\anaconda3\lib\site-packages (from shap>=0.28.5->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (4.66.4)
Requirement already satisfied: slicer==0.0.8 in c:\users\asus\anaconda3\lib\site-packages (from shap>=0.28.5->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.0.8)
Requirement already satisfied: numba>=0.54 in c:\users\asus\anaconda3\lib\site-packages (from shap>=0.28.5->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.59.1)
Requirement already satisfied: cloudpickle in c:\users\asus\anaconda3\lib\site-packages (from shap>=0.28.5->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.2.1)
Requirement already satisfied: pycparser in c:\users\asus\anaconda3\lib\site-packages (from cffi>=1.17.1->gevent>=1.3.6->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.21)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\asus\anaconda3\lib\site-packages (from Flask<3.1,>=1.0.4->dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (3.1.4)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\asus\anaconda3\lib\site-packages (from Flask<3.1,>=1.0.4->dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.2.0)
Requirement already satisfied: click>=8.1.3 in c:\users\asus\anaconda3\lib\site-packages (from Flask<3.1,>=1.0.4->dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in c:\users\asus\anaconda3\lib\site-packages (from Flask<3.1,>=1.0.4->dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (1.6.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\asus\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.8.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\asus\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel>=4.10.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\users\asus\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel>=4.10.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (305.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib>=3.5->SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib>=3.5->SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib>=3.5->SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib>=3.5->SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (1.4.4)
Requirement already satisfied: pillow>=8 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib>=3.5->SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\asus\anaconda3\lib\site-packages (from matplotlib>=3.5->SALib>=1.3.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (3.0.9)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in c:\users\asus\anaconda3\lib\site-packages (from numba>=0.54->shap>=0.28.5->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.42.0)
Requirement already satisfied: wcwidth in c:\users\asus\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.2.5)
Requirement already satisfied: six>=1.5 in c:\users\asus\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.19.2->interpret-core==0.7.3->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\asus\anaconda3\lib\site-packages (from Werkzeug<3.1->dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.1.3)
Requirement already satisfied: zipp>=0.5 in c:\users\asus\anaconda3\lib\site-packages (from importlib-metadata->dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (3.17.0)
Requirement already satisfied: executing in c:\users\asus\anaconda3\lib\site-packages (from stack-data->ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.8.3)
Requirement already satisfied: asttokens in c:\users\asus\anaconda3\lib\site-packages (from stack-data->ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\asus\anaconda3\lib\site-packages (from stack-data->ipython>=5.5.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.3->interpret) (0.2.2)
Note: you may need to restart the kernel to use updated packages.

In [33]:
X
y
X_train
X_test
y_train
y_test

371      0
26192    1
64632    1
19700    0
16362    0
        ..
46090    1
33999    0
47571    0
6598     0
20691    0
Name: cardio, Length: 13688, dtype: int64

In [34]:
from interpret.glassbox import ExplainableBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report

In [35]:
ebm = ExplainableBoostingClassifier(
    random_state=42,
    max_bins=256
)

ebm.fit(X_train, y_train)

ExplainableBoostingClassifier(max_bins=256)

In [36]:
y_pred_ebm = ebm.predict(X_test)

print("EBM Accuracy:", accuracy_score(y_test, y_pred_ebm))
print(classification_report(y_test, y_pred_ebm))

EBM Accuracy: 0.739406779661017
              precision    recall  f1-score   support

           0       0.72      0.79      0.75      6910
           1       0.76      0.69      0.72      6778

    accuracy                           0.74     13688
   macro avg       0.74      0.74      0.74     13688
weighted avg       0.74      0.74      0.74     13688

In [38]:
from interpret import show

In [39]:
ebm_global = ebm.explain_global()
show(ebm_global)

In [43]:
import joblib

joblib.dump(lr, "logistic_model.pkl")

['logistic_model.pkl']

In [44]:
import joblib

joblib.dump(ebm, "ebm_model.pkl")

['ebm_model.pkl']

In [45]:
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [46]:
joblib.dump(X.columns.tolist(), "feature_names.pkl")

['feature_names.pkl']

In [1]:
import os
os.getcwd()

'C:\\Users\\ASUS'